#-------------------------------
# Site Settings
title: Lantern Thoughts
description: Reflections on life, creativity, technology, and imagined worlds.
logo: #### #/images/logo.png
logo_dark:
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Writing"
      url: "/writing/"
    - title: "Tech"
      url: "/tech/"
    - title: "TTRPG"
      url: "/ttrpg/"
    - title: "About"
      url: "/about/"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Lantern Thoughts by Cameron Sparks
  hero_description: A small light for big ideas â€” reflections on life, creativity, technology, and the stories we tell when the day grows quiet.
  hero_image: '/images/hero_image_no_text.png'


#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Subscribe here
  mailchimp_button_text: Get a new tip


#-------------------------------
# Author Settings
author:
  author_name: Cameron Sparks
  author_bio: Reflections on life, creativity, technology, and imagined worlds.
  author_avatar: 'https://github.com/sparks-cam/lanternthoughts/releases/download/assets-v1/author_image.webp'


social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-square-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Gallery Footer Section
gallery:
  enable: true
  gallery_title: Gallery
  gallery_columns: 3
  gallery_images:
    - alt: 'TTRPG'
      url: 'https://github.com/sparks-cam/lanternthoughts/releases/download/assets-v1/ttrpg_hub_hero.webp'
    - alt: 'Lifestyle'
      url: '/images/101.jpg'
    - alt: 'Hobby'
      url: '/images/102.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  form_id: sparks.cam@protonmail.com # Add your form_id
  description: Reflections on life, creativity, technology, and imagined worlds. # Add a description of your form

# NOTE
# Menca theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id